A = int(input("Please enter your first number:"))
B = int(input("Please enter your second number:"))
print("Sum:",A+B)
print("Difference:",A-B)
print("Product:",A*B)
print("Average:",(A+B)/2)
print("Distance:",abs(A-B))
print("Maximum:",max(A,B))
print("Minimum:",min(A,B))
